### ISSUE TITLE
NextAnswerの固定

### ISSUE THREAD

**Issue by moezakura** [uryoya/enquete#1]
これでは次の表示するページが固定されてしまっているのでは
> https://github.com/uryoya/enquete/commit/211936c537ef7bf0de01d7b5a2173ec6a8909d35#commitcomment-24327023

**Comment by uryoya** [comment]
https://github.com/uryoya/enquete/commit/d76b065aa53f33920b5646cdb56b641fb952ac2e 修正しました :muscle:

**Comment by uryoya** [comment]
djangoやりながらテスト導入せねばって思った()
